// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: task-manager.proto

package task_manager_grpc_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoneTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneTaskRequest) Reset() {
	*x = DoneTaskRequest{}
	mi := &file_task_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneTaskRequest) ProtoMessage() {}

func (x *DoneTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneTaskRequest.ProtoReflect.Descriptor instead.
func (*DoneTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{5}
}

func (x *DoneTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_task_manager_proto protoreflect.FileDescriptor

const file_task_manager_proto_rawDesc = "" +
	"\n" +
	"\x12task-manager.proto\x12\x15TaskManagerProtoFiles\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x10\n" +
	"\x0eGetTaskRequest\"R\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"D\n" +
	"\x0fGetTaskResponse\x121\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1b.TaskManagerProtoFiles.TaskR\x05tasks\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fDoneTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xd3\x02\n" +
	"\vTaskManager\x12N\n" +
	"\n" +
	"CreateTask\x12(.TaskManagerProtoFiles.CreateTaskRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\aGetTask\x12%.TaskManagerProtoFiles.GetTaskRequest\x1a&.TaskManagerProtoFiles.GetTaskResponse\x12N\n" +
	"\n" +
	"DeleteTask\x12(.TaskManagerProtoFiles.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\bDoneTask\x12&.TaskManagerProtoFiles.DoneTaskRequest\x1a\x16.google.protobuf.EmptyBIZGgithub.com/NikitaKh06/TaskManagerProtoFiles/task-manager-grpc-generatedb\x06proto3"

var (
	file_task_manager_proto_rawDescOnce sync.Once
	file_task_manager_proto_rawDescData []byte
)

func file_task_manager_proto_rawDescGZIP() []byte {
	file_task_manager_proto_rawDescOnce.Do(func() {
		file_task_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_manager_proto_rawDesc), len(file_task_manager_proto_rawDesc)))
	})
	return file_task_manager_proto_rawDescData
}

var file_task_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_task_manager_proto_goTypes = []any{
	(*CreateTaskRequest)(nil), // 0: TaskManagerProtoFiles.CreateTaskRequest
	(*GetTaskRequest)(nil),    // 1: TaskManagerProtoFiles.GetTaskRequest
	(*Task)(nil),              // 2: TaskManagerProtoFiles.Task
	(*GetTaskResponse)(nil),   // 3: TaskManagerProtoFiles.GetTaskResponse
	(*DeleteTaskRequest)(nil), // 4: TaskManagerProtoFiles.DeleteTaskRequest
	(*DoneTaskRequest)(nil),   // 5: TaskManagerProtoFiles.DoneTaskRequest
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
}
var file_task_manager_proto_depIdxs = []int32{
	2, // 0: TaskManagerProtoFiles.GetTaskResponse.tasks:type_name -> TaskManagerProtoFiles.Task
	0, // 1: TaskManagerProtoFiles.TaskManager.CreateTask:input_type -> TaskManagerProtoFiles.CreateTaskRequest
	1, // 2: TaskManagerProtoFiles.TaskManager.GetTask:input_type -> TaskManagerProtoFiles.GetTaskRequest
	4, // 3: TaskManagerProtoFiles.TaskManager.DeleteTask:input_type -> TaskManagerProtoFiles.DeleteTaskRequest
	5, // 4: TaskManagerProtoFiles.TaskManager.DoneTask:input_type -> TaskManagerProtoFiles.DoneTaskRequest
	6, // 5: TaskManagerProtoFiles.TaskManager.CreateTask:output_type -> google.protobuf.Empty
	3, // 6: TaskManagerProtoFiles.TaskManager.GetTask:output_type -> TaskManagerProtoFiles.GetTaskResponse
	6, // 7: TaskManagerProtoFiles.TaskManager.DeleteTask:output_type -> google.protobuf.Empty
	6, // 8: TaskManagerProtoFiles.TaskManager.DoneTask:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_manager_proto_init() }
func file_task_manager_proto_init() {
	if File_task_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_manager_proto_rawDesc), len(file_task_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_manager_proto_goTypes,
		DependencyIndexes: file_task_manager_proto_depIdxs,
		MessageInfos:      file_task_manager_proto_msgTypes,
	}.Build()
	File_task_manager_proto = out.File
	file_task_manager_proto_goTypes = nil
	file_task_manager_proto_depIdxs = nil
}
